filebeat.inputs:
- type: mqtt
  hosts: 
    - tcp://hivemq001:1883
  username: realtime
  password: realtimepassword
  topics: 
    - '#'
  fields_under_root: true
  processors:
    - decode_json_fields:
        fields:
          - message
        process_array: false
        max_depth: 1
        target: ''
        overwrite_keys: false
        add_error_key: true
  tags: ["mqtt_traffic"]
  fields:
    app_id: my_mqtt_usecase

output.elasticsearch:
  hosts: 'https://es01:9200'
  username: 'elastic'
  password: 'elastic'
  ssl:
    certificate_authorities: "/usr/share/elasticsearch/config/certs/ca/ca.crt"
    certificate: "/usr/share/elasticsearch/config/certs/filebeat/filebeat.crt"
    key: "/usr/share/elasticsearch/config/certs/filebeat/filebeat.key"